# Generated by Django 2.0.13 on 2021-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsc', models.CharField(max_length=15)),
                ('timestamp', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=75)),
                ('number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
