# Generated by Django 2.0.13 on 2021-08-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
