# Generated by Django 2.0.13 on 2021-08-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_auto_20210804_0221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='sms',
            new_name='smsc',
        ),
    ]
